version: "2"
services:
  test:
    build: .
    environment:
        REDIS_HOST: redis:6379
        LOGSTASH_HOST: logstash
        LOGSTASH_PORT: 8515
        PROJECT: "lock"
    command: sh -c "./wait_for.sh redis 6379 && ./wait_for.sh logstash 8515 20 udp && go test -cover"
    links:
      - redis
      - logstash
    depends_on:
      - redis
      - logstash
  redis:
    image: redis
    ports:
      - "6379:6379"
  logstash:
    command: " -e 'input { udp { port => 8515  codec => json } } output { stdout { } }'"
    image: logstash
    ports:
      - "8515:8515"
